title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Luiza Garzim # add your name
author-img: luizagarzim.jpg # add your photo
about-author: Atuo em desenvolvimento de sistemas há 10 anos na mais diversas linguagens (MESMO).
  Atualmente engenheira de Software na SouSmile.
  Mãe do Henrique e no processo de descobrimento de como uma pessoa que quer ser exemplo
  pro filho pode ser poderosa. # add description
social-twitter: luizagarzim # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: luizagarzim # add your Github handle
social-linkedin: luizagarzim # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
